### PR TITLE
fix whispers display and not sending in case of double spaces before name

### LINKED ISSUE #1053: whisper via command issue
When issuing a whisper via a command, your sent whisper does not show up in your "whispers" tab. 

https://i.imgur.com/9htXASC.gifv

### PR DESCRIPTION
**Pull request by hemirt**
fix #1053 #1058

### CODE REVIEW

File: src/controllers/commands/CommandController.cpp [hunk 1]
```diff
@@ -31,6 +32,136 @@
...
+    QStringList words = text.split(' ', QString::SkipEmptyParts);
+
+    if (words.length() == 0)
+    {
+        return false;
+    }
+
+    QString commandName = words[0];
+
+    if (commandName == "/w")
```
Comment (pajlada) [inline src/controllers/commands/CommandController.cpp]: Make a `QStringList` containing "/w" and ".w" and use its contains operator to check if it's a whisper instead. make sure to supply the `Qt::CaseInsensitive` argument. This comment applies to other places you've touched that checks if something is a whisper

File: src/controllers/commands/CommandController.cpp [hunk 2]
```diff
@@ -31,6 +32,136 @@
...
+        app->twitch.server->forEachChannel(
+            [&messagexD, overrideFlags](ChannelPtr _channel) {
+                _channel->addMessage(messagexD, overrideFlags);
+            });
+    }
+
+    return true;
+}
+
+bool appendWhisperMessageLocally(const QString &textNoEmoji)
```
Comment (pajlada) [inline src/controllers/commands/CommandController.cpp]: Please don't use operator overloading with these two functions, call them separate names since the parameters are so similar.

File: src/controllers/commands/CommandController.cpp [hunk 3]
```diff
@@ -518,7 +554,15 @@ QString CommandController::execCustomCommand(const QStringList &words,
...
 
-    return result.replace("{{", "{");
+    auto res = result.replace("{{", "{");
+
+    if (dryRun)
+    {
+        return res;
+    }
+
+    return appendWhisperMessageLocally(res) ? (sendWhisperMessage(res), "")
```
Comment (pajlada) [inline src/controllers/commands/CommandController.cpp]: Expand this to a logical if-statement instead of using a ternary operator. also what does `(sendWhisperMessage(res), "")` do? does that execute sendWhisperMessage and return an empty string?

File: src/controllers/commands/CommandController.cpp [hunk 4]
```diff
@@ -31,6 +32,136 @@
             "/followersoff"                                             \
     }
 
+namespace {
+using namespace chatterino;
+
+void sendWhisperMessage(const QString &text)
+{
+    auto app = getApp();
+    app->twitch.server->sendMessage("jtv", text.simplified());
```
Comment (pajlada) [inline src/controllers/commands/CommandController.cpp]: please add a comment here stating that we should not be sending whispers through jtv, but rather to your own username

File: src/controllers/commands/CommandController.cpp (hunk 3 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: yes, a comma operator
sure

File: src/controllers/commands/CommandController.cpp (hunk 4 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: I don't understand, but okay, but i believe you should be using the chat youre currently writing in, because the error messages get sent on the same channel, thats why I added "jtv" channel to the "global" error messages checks https://github.com/fourtf/chatterino2/blob/e201881516a06f8cd14038ac7e6b32cc034404f8/src/providers/twitch/IrcMessageHandler.cpp#L532

Comment (pajlada) [reply src/controllers/commands/CommandController.cpp]: Sending whispers to your own channel means you will not be rate-limited, which can happen if you send whispers to jtv

File: src/controllers/commands/CommandController.cpp (hunk 1 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L158

https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L260

File: src/controllers/commands/CommandController.cpp (hunk 2 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L48

https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L146

File: src/controllers/commands/CommandController.cpp (hunk 3 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L563-L571

File: src/controllers/commands/CommandController.cpp (hunk 4 above)
Comment (hemirt) [reply src/controllers/commands/CommandController.cpp]: https://github.com/fourtf/chatterino2/blob/b7d04a648ff7ab584c07f5d9d58defe89b393253/src/controllers/commands/CommandController.cpp#L42-L43

**Comment by hemirt** [comment]
resolved comments

**Comment by pajlada** [comment]
Thank you for your contribution! LGTM :+1:
